from __future__ import annotations

RU = {
    "who": "Кто занимается",
    "welcome": (
        "⚡️ Школа открыта. В зале два учителя.\n\n"
        "Тихий ставит стопу на пол и считает дыхание. "
        "Школа героя даёт шагу имя: Ведьмак, Тор, Чёрная Вдова, Валькирия.\n\n"
        "Если готов, выбери, кем входишь."
    ),
    "calm": "Спокойная школа",
    "active": "Активная школа",
    "where": "Выбери час. От него зависит занятие.",
    "train_title": "Тренировка",
    "menu_title": "Меню",
    "pay_title": "Подписка",
    "pay_body": "Дальше нужна подписка. Запрос уже у администратора.",
    "gathering": "Собираю занятие. Около двух минут.",
    "timer_running": "Таймер: {clock}",
    "timer_done": "Время.",
    "timer_wait": "Таймер включится на занятии.",
    "accepted": "Принял.",
    "use_buttons": "Нажми кнопку внизу.",
    "fail": "Занятие не собралось. Нажми тренировку ещё раз.",
    "hour_saved": "Час записан",
    "schools_title": "Школы",
    "exp_title": "Опыт",
    "count_line": "Счёт этой пары: {hours}",
    "length_line": "Длина занятия: {minutes} мин",
    "reps_line": "{n} раз",
    "archive_title": "Архив",
    "continue_line": "Занятие открыто. Листай.",
    "note_invite": "Напиши, что поправить.",
    "review_invite": "Напиши отзыв одним сообщением.",
    "review_sent": "Отзыв отправлен.",
    "delete_ask": "Удалить все данные этого чата? Вернуть их будет нельзя.",
    "deleted": "Данные удалены.",
    "btn_delete_yes": "Да, удалить",
    "btn_delete_no": "Оставить",
    "next_time": "Этот час сохранится для следующей тренировки.",
    "btn_male": "♂️  Мужчина",
    "btn_female": "♀️  Женщина",
    "btn_yoga": "🧘  Йога",
    "btn_qigong": "🌊  Цигун",
    "btn_beloyar": "🌿  Белояр",
    "btn_monk": "🔔  Монах",
    "btn_witcher": "🐺  Ведьмак",
    "btn_blade": "⚔️  Блэйд",
    "btn_thor": "🔨  Тор",
    "btn_spider": "🕷  Человек-паук",
    "btn_widow": "🕸  Чёрная Вдова",
    "btn_elektra": "🗡  Электра",
    "btn_valkyrie": "⚡️  Валькирия",
    "btn_nikita": "🕵️‍♀️  Никита",
    "btn_morning": "🌅  Утро",
    "btn_day": "☀️  День",
    "btn_evening": "🌆  Вечер",
    "btn_night": "🌙  Ночь",
    "btn_outdoor": "🌲  На улице",
    "btn_train": "▶️  Тренировка",
    "btn_menu": "☰  Меню",
    "btn_back": "⬅️  Назад",
    "btn_next": "➡️  Дальше",
    "btn_timer": "⏱  Таймер",
    "btn_time": "🕒  Время суток",
    "btn_schools": "✨  Школы",
    "btn_exp": "📈  Опыт",
    "btn_change": "🔄  Сменить",
    "progress": "Прогресс: [{n}/10000] — {pct}",
}

EN = {
    "who": "Who is training",
    "welcome": (
        "⚡️ The school is open. Two teachers share the hall.\n\n"
        "The quiet one sets the foot on the floor and counts the breath. "
        "The hero school gives the step a name: the Witcher, Thor, Black Widow, Valkyrie.\n\n"
        "If you are ready, choose how you enter."
    ),
    "calm": "Calm school",
    "active": "Active school",
    "where": "Choose the hour. It shapes the session.",
    "train_title": "Training",
    "menu_title": "Menu",
    "pay_title": "Subscription",
    "pay_body": "The next sessions need a subscription. The request is already with the administrator.",
    "gathering": "Putting the session together. About two minutes.",
    "timer_running": "Timer: {clock}",
    "timer_done": "Time.",
    "timer_wait": "The timer starts on the session.",
    "accepted": "Got it.",
    "use_buttons": "Press a button below.",
    "fail": "The session failed. Press training again.",
    "hour_saved": "Hour recorded",
    "schools_title": "Schools",
    "exp_title": "Experience",
    "count_line": "This pair: {hours}",
    "length_line": "Session length: {minutes} min",
    "reps_line": "{n} reps",
    "archive_title": "Archive",
    "continue_line": "The session is open. Keep going.",
    "note_invite": "Write what to adjust.",
    "review_invite": "Write the review in one message.",
    "review_sent": "Review sent.",
    "delete_ask": "Delete everything from this chat? It cannot be restored.",
    "deleted": "Data deleted.",
    "btn_delete_yes": "Yes, delete",
    "btn_delete_no": "Keep",
    "next_time": "This hour stays for the next session.",
    "btn_male": "♂️  Man",
    "btn_female": "♀️  Woman",
    "btn_yoga": "🧘  Yoga",
    "btn_qigong": "🌊  Qigong",
    "btn_beloyar": "🌿  Beloyar",
    "btn_monk": "🔔  Monk",
    "btn_witcher": "🐺  Witcher",
    "btn_blade": "⚔️  Blade",
    "btn_thor": "🔨  Thor",
    "btn_spider": "🕷  Spider-Man",
    "btn_widow": "🕸  Black Widow",
    "btn_elektra": "🗡  Elektra",
    "btn_valkyrie": "⚡️  Valkyrie",
    "btn_nikita": "🕵️‍♀️  Nikita",
    "btn_morning": "🌅  Morning",
    "btn_day": "☀️  Day",
    "btn_evening": "🌆  Evening",
    "btn_night": "🌙  Night",
    "btn_outdoor": "🌲  Outdoors",
    "btn_train": "▶️  Training",
    "btn_menu": "☰  Menu",
    "btn_back": "⬅️  Back",
    "btn_next": "➡️  Next",
    "btn_timer": "⏱  Timer",
    "btn_time": "🕒  Time of day",
    "btn_schools": "✨  Schools",
    "btn_exp": "📈  Experience",
    "btn_change": "🔄  Change",
    "progress": "Progress: [{n}/10000] — {pct}",
}
