from __future__ import annotations

SEP = "-__________________________/"

RU = {
    "sep": SEP,
    "who": "Кто занимается",
    "welcome": (
        "-__________________________/\n\n"
        "Ты стоишь у порога долгой подготовки.\n\n"
        "Это не игра и не короткая зарядка. Час за часом тело станет тише, точнее и сильнее. "
        "Спокойная школа будет беречь суставы и дыхание. Активная вырастит силу, шаг и выдержку. "
        "Шкала длинная: до её конца доходят годами, не за один сезон.\n\n"
        "Если готов, выбери, кем входишь.\n\n"
        "-__________________________/"
    ),
    "calm": "Спокойная школа",
    "active": "Активная школа",
    "where": "Куда идём",
    "train_title": "Тренировка",
    "menu_title": "Меню",
    "pay_title": "Подписка",
    "pay_body": "Дальше занятия открывает подписка. Запрос уже у администратора.",
    "gathering": "Собираю занятие.",
    "timer_running": "Таймер: {clock}",
    "timer_done": "Время.",
    "timer_wait": "Таймер встанет на упражнении.",
    "accepted": "Принял.",
    "use_buttons": "Нажми кнопку внизу.",
    "fail": "Не вышло собрать занятие. Нажми тренировку ещё раз.",
    "hour_saved": "Час записан",
    "schools_title": "Школы",
    "exp_title": "Опыт",
    "count_line": "Счёт этой пары: {hours}",
    "length_line": "Длина занятия: {minutes} мин",
    "archive_title": "Архив",
    "continue_line": "Занятие открыто. Листай дальше.",
    "note_invite": "Если хочешь, напиши, что поправить.",
    "next_time": "Время суток сохранится для следующей тренировки.",
    "btn_male": "♂️  Мужчина",
    "btn_female": "♀️  Женщина",
    "btn_yoga": "🧘  Йога",
    "btn_qigong": "🌊  Цигун",
    "btn_beloyar": "🌿  Белояр",
    "btn_monk": "🔔  Монах",
    "btn_witcher": "🐺  Ведьмак",
    "btn_blade": "⚔️  Блэйд",
    "btn_thor": "🔨  Тор",
    "btn_spider": "🕷  Человек-паук",
    "btn_widow": "🕸  Чёрная Вдова",
    "btn_elektra": "🗡  Электра",
    "btn_valkyrie": "⚡️  Валькирия",
    "btn_nikita": "🎖  Никита",
    "btn_morning": "🌅  Утро",
    "btn_day": "☀️  День",
    "btn_evening": "🌆  Вечер",
    "btn_night": "🌙  Ночь",
    "btn_outdoor": "🌲  На улице",
    "btn_train": "▶️  Тренировка",
    "btn_menu": "☰  Меню",
    "btn_back": "⬅️  Назад",
    "btn_next": "➡️  Дальше",
    "btn_timer": "⏱  Таймер",
    "btn_time": "🕒  Время суток",
    "btn_schools": "✨  Школы",
    "btn_exp": "📈  Опыт",
    "btn_change": "🔄  Сменить",
    "btn_r1": "1  Очень легко",
    "btn_r2": "2  Легко",
    "btn_r3": "3  В самый раз",
    "btn_r4": "4  Тяжело",
    "btn_r5": "5  На пределе",
    "progress": "Прогресс: [{n}/10000] — {pct}",
}

EN = {
    "sep": SEP,
    "who": "Who is training",
    "welcome": (
        "-__________________________/\n\n"
        "You stand at the threshold of a long preparation.\n\n"
        "This is not a game and not a short workout. Hour by hour the body grows quieter, sharper, and stronger. "
        "The calm school keeps the joints and the breath. The active school builds strength, step, and stamina. "
        "The scale is long: its end takes years, not a season.\n\n"
        "If you are ready, choose how you enter.\n\n"
        "-__________________________/"
    ),
    "calm": "Calm school",
    "active": "Active school",
    "where": "Where we go",
    "train_title": "Training",
    "menu_title": "Menu",
    "pay_title": "Subscription",
    "pay_body": "The next sessions open with a subscription. The request is already with the administrator.",
    "gathering": "Putting the session together.",
    "timer_running": "Timer: {clock}",
    "timer_done": "Time.",
    "timer_wait": "The timer starts on an exercise.",
    "accepted": "Got it.",
    "use_buttons": "Press a button below.",
    "fail": "The session did not come together. Press training again.",
    "hour_saved": "Hour recorded",
    "schools_title": "Schools",
    "exp_title": "Experience",
    "count_line": "This pair: {hours}",
    "length_line": "Session length: {minutes} min",
    "archive_title": "Archive",
    "continue_line": "The session is open. Keep turning the pages.",
    "note_invite": "If you want, write what to adjust.",
    "next_time": "The time of day will be used for the next session.",
    "btn_male": "♂️  Man",
    "btn_female": "♀️  Woman",
    "btn_yoga": "🧘  Yoga",
    "btn_qigong": "🌊  Qigong",
    "btn_beloyar": "🌿  Beloyar",
    "btn_monk": "🔔  Monk",
    "btn_witcher": "🐺  Witcher",
    "btn_blade": "⚔️  Blade",
    "btn_thor": "🔨  Thor",
    "btn_spider": "🕷  Spider-Man",
    "btn_widow": "🕸  Black Widow",
    "btn_elektra": "🗡  Elektra",
    "btn_valkyrie": "⚡️  Valkyrie",
    "btn_nikita": "🎖  Nikita",
    "btn_morning": "🌅  Morning",
    "btn_day": "☀️  Day",
    "btn_evening": "🌆  Evening",
    "btn_night": "🌙  Night",
    "btn_outdoor": "🌲  Outdoors",
    "btn_train": "▶️  Training",
    "btn_menu": "☰  Menu",
    "btn_back": "⬅️  Back",
    "btn_next": "➡️  Next",
    "btn_timer": "⏱  Timer",
    "btn_time": "🕒  Time of day",
    "btn_schools": "✨  Schools",
    "btn_exp": "📈  Experience",
    "btn_change": "🔄  Change",
    "btn_r1": "1  Very easy",
    "btn_r2": "2  Easy",
    "btn_r3": "3  Just right",
    "btn_r4": "4  Hard",
    "btn_r5": "5  At the limit",
    "progress": "Progress: [{n}/10000] — {pct}",
}
