"""character creation steps

Revision ID: d5181ae2f2c3
Revises: 490b50727618
Create Date: 2026-10-02 18:40:04.391395
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd5181ae2f2c3'
down_revision: Union[str, None] = '490b50727618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('creation_step', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('characters', sa.Column('creation_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'creation_data')
    op.drop_column('characters', 'creation_step')
    # ### end Alembic commands ###
