"""initial schema

Revision ID: 490b50727618
Revises: 
Create Date: 2026-10-02 17:26:30.953043
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '490b50727618'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('temperature', sa.Float(), server_default='0.7', nullable=False),
    sa.Column('max_tokens', sa.Integer(), server_default=sa.text('2000'), nullable=False),
    sa.Column('max_history_messages', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('compression_threshold', sa.Integer(), server_default=sa.text('18'), nullable=False),
    sa.Column('system_prompt_version', sa.String(length=32), server_default='v1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_users', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('active_subscriptions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('trial_users', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('expired_users', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('banned_users', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('dau', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('mau', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('messages_today', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('prompt_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('completion_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('cache_hit_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('cache_rate', sa.Float(), server_default='0', nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), server_default='0', nullable=False),
    sa.Column('successful_payments', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('revenue_rub', sa.Float(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('prompt_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('security_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_log_event_type'), 'security_log', ['event_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('subscription_status', sa.String(length=16), server_default='trial', nullable=False),
    sa.Column('trial_started', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agreed_to_privacy', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('privacy_agreed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('payment_method_id', sa.String(length=128), nullable=True),
    sa.Column('last_payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('messages_today', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('daily_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_banned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('is_tester', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('race', sa.String(length=64), nullable=True),
    sa.Column('char_class', sa.String(length=64), nullable=True),
    sa.Column('subclass', sa.String(length=64), nullable=True),
    sa.Column('background', sa.String(length=64), nullable=True),
    sa.Column('alignment', sa.String(length=32), nullable=True),
    sa.Column('level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('xp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('game_day', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('hp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_hp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ac', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('speed', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('attack_bonus', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('spell_dc', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('strength', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('dexterity', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('constitution', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('intelligence', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('wisdom', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('charisma', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('gold', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('silver', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('arrows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('bolts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rations', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('oil', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('exhaustion', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('inspiration', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('weapon_name', sa.Text(), nullable=True),
    sa.Column('armor_name', sa.Text(), nullable=True),
    sa.Column('spells', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('spell_slots', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('companion_name', sa.String(length=128), nullable=True),
    sa.Column('companion_hp', sa.Integer(), nullable=True),
    sa.Column('companion_max_hp', sa.Integer(), nullable=True),
    sa.Column('companion_loyalty', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('world_tension', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('in_combat', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_resting', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_created', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=True)
    op.create_table('encyclopedia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_name', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_name', name='uq_encyclopedia_user')
    )
    op.create_index(op.f('ix_encyclopedia_user_id'), 'encyclopedia', ['user_id'], unique=False)
    op.create_table('faction_reputation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('faction_name', sa.String(length=128), nullable=False),
    sa.Column('reputation', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'faction_name', name='uq_faction_user')
    )
    op.create_index(op.f('ix_faction_reputation_user_id'), 'faction_reputation', ['user_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slot_index', name='uq_inventory_slot')
    )
    op.create_index(op.f('ix_inventory_user_id'), 'inventory', ['user_id'], unique=False)
    op.create_table('message_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_hit_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_history_created_at'), 'message_history', ['created_at'], unique=False)
    op.create_index('ix_message_history_user_created', 'message_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_message_history_user_id'), 'message_history', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('robokassa_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('type', sa.String(length=16), server_default='one_time', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('story_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('messages_covered', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_summaries_user_id'), 'story_summaries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_summaries_user_id'), table_name='story_summaries')
    op.drop_table('story_summaries')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_message_history_user_id'), table_name='message_history')
    op.drop_index('ix_message_history_user_created', table_name='message_history')
    op.drop_index(op.f('ix_message_history_created_at'), table_name='message_history')
    op.drop_table('message_history')
    op.drop_index(op.f('ix_inventory_user_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_faction_reputation_user_id'), table_name='faction_reputation')
    op.drop_table('faction_reputation')
    op.drop_index(op.f('ix_encyclopedia_user_id'), table_name='encyclopedia')
    op.drop_table('encyclopedia')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_log_event_type'), table_name='security_log')
    op.drop_table('security_log')
    op.drop_table('prompt_modules')
    op.drop_table('game_analytics')
    op.drop_table('ai_settings')
    # ### end Alembic commands ###
